---
# tasks file for network_time
- name: Ensure required variables are defined
  fail: 
    msg: "Variable '{{ item }}' is not defined"
  when: item is undefined
  with_items: "{{ required_vars }}"

